#!/bin/bash

echo "Github events"
curl --header 'Accept: application/json' 'https://api.github.com/users/warpr/events' > github.events.json
echo "Bitbucket events"
curl 'https://bitbucket.org/warp/profile/activity' > bitbucket.events.html
echo "Twitter events"
curl 'https://mobile.twitter.com/byld' > twitter.events.html
echo "warpr.org events"
curl 'https://warpr.org/atom/' > warpr.org.atom.xml
echo "frob.nl blog events"
curl 'https://frob.nl/blog/atom/' > blog.atom.xml
echo "identi.ca events"
curl 'https://identi.ca/warp/' | grep initialData | sed 's/.*initialData = //' | sed 's/;$//' | jsonindent > identi.ca.json
echo "stackoverflow events"
curl 'http://stackoverflow.com/feeds/user/7700' > stackoverflow.atom.xml
echo "done"

